version: "3.3"

services:
  nginx:
    container_name: nginx
    build: images/nginx
    command: nginx -g "daemon off;"
    links:
      - php
    ports:
      - "9001:80"

  php:
    container_name: php
    user: root
    build: images/php
    volumes:
      - ./laravel:/var/www/html
    working_dir: /var/www/html
    command: php-fpm